import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "sonner";
import { Roboto, Ubuntu_Sans } from "next/font/google";
const geistSans = Ubuntu_Sans({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700"],
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} $antialiased`}>
        <Toaster position="top-center" />
        {children}
      </body>
    </html>
  );
}
